#!/usr/bin/env node
// @ts-check

/**
 * build-report.mjs — M0-RECONCILIATION-REPORT.
 *
 * The M0 acceptance criterion from the brief: one CSV plus a
 * reconciliation report stating what came from where and what was
 * dropped.
 *
 * Both artefacts come from ONE call to buildDataset(), so the report's
 * counts cannot drift from the CSV it describes. Every count is
 * reproducible from the frozen inputs named in
 * data/archive-manifest.json, whose digests are quoted here.
 *
 * The report carries a machine-readable summary block so the gate can
 * assert that its numbers still equal a fresh build.
 *
 * Usage: node tools/build-report.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { buildDataset } from './build-dataset.mjs';
import { SOURCED_FIELDS, toCsv } from './lib/dataset.mjs';

const ARCHIVE = 'Pre August 2026';
const MANIFEST = 'data/archive-manifest.json';
const CSV_OUT = 'data/deep-groove-v1.csv';
const REPORT_OUT = 'data/reconciliation-report.md';

/** Sources actually read by an import, in the order they were read. */
const READ = [
  ['Vinyl Records Record 2 Jen.xlsx', 'Classical Master + Classical Remedial'],
  ['2nd load to add.xlsx', 'Sheet1'],
  ['1st load to add.xlsx', 'Sheet1 (2)'],
  ['AI Works/v1/AI_Vinyl_Works_Stage_8 AI Data update.xlsx', 'Classical Master'],
  ['AI Works/v2/classical Track listings 01.xlsx', 'Sheet1'],
];

/** Frozen and checksummed, but deliberately not imported. */
const NOT_READ = [
  ['Vinyl Records Record.xlsx', 'superseded by Record 2 Jen'],
  ['Vinyl Records Record 2.xlsx', 'superseded; byte-identical to Record 3'],
  ['Vinyl Records Record 3.xlsx', 'superseded; byte-identical to Record 2'],
  ['classical vinyl list in progress.csv', 'a MacRoman export of the same 351 Remedial rows'],
];

export function renderReport() {
  const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));
  const digest = new Map(manifest.files.map((/** @type {any} */ f) => [f.path, f]));
  const { rows, stats, droppedIds, mergeDecisions } = buildDataset(ARCHIVE);

  const enriched = stats['M0-IMPORT-ENRICHED'];
  const remedial = stats['M0-IMPORT-REMEDIAL'];
  const load = stats['M0-MERGE-LOAD-FILES'];
  const ai = stats['M0-IMPORT-AI-WORKS'];

  /** @type {Record<string, number>} */ const provenance = {};
  for (const row of rows) {
    for (const f of SOURCED_FIELDS) {
      const s = row[`${f}_source`];
      if (s) provenance[s] = (provenance[s] ?? 0) + 1;
    }
  }

  const summary = {
    generatedFrom: MANIFEST,
    archiveFileCount: manifest.fileCount,
    datasetRows: rows.length,
    byBatch: {
      'M0-IMPORT-ENRICHED': enriched.rows,
      'M0-IMPORT-REMEDIAL': remedial.imported,
      'M0-MERGE-LOAD-FILES': load.merged,
    },
    dropped: {
      remedialPlaceholders: remedial.droppedPlaceholders,
      loadFilePlaceholders: load.sheetRows - load.usable,
      loadFileDuplicates: load.duplicates,
    },
    splitOutcomes: remedial.splitOutcomes,
    provenanceValues: provenance,
    decisionEligibleRows: rows.filter((r) => r.decision_eligible === 'yes').length,
  };

  const row = (/** @type {string} */ path) => {
    const d = digest.get(path);
    return d ? `\`${d.sha256.slice(0, 12)}…\` | ${d.bytes.toLocaleString('en-GB')} B` : '— | —';
  };

  const report = `# M0 reconciliation report

<!-- GENERATED by tools/build-report.mjs — never hand-edit.
     Regenerate: node tools/build-report.mjs -->

One reconciled dataset — \`${CSV_OUT}\` — built from the frozen archive.
Every count below is reproducible from the inputs named here, and the
gate asserts these numbers still equal a fresh build.

**Dataset: ${rows.length} rows.** ${enriched.rows} enriched +
${remedial.imported} backlog + ${load.merged} merged from the load
files. That is the brief's "446 already catalogued"; the ~300 further
records are the physical backlog, which has never been entered.

**Nothing in this dataset may feed a decision yet.** ${summary.decisionEligibleRows}
rows are decision-eligible, which is the correct end state for a pure
import: no value has been confirmed by a person, and nothing was
captured off the shelf.

## Inputs read

| Source | Sheet | Digest | Size |
|---|---|---|---|
${READ.map(([f, s]) => `| \`${f}\` | ${s} | ${row(f)} |`).join('\n')}

## Frozen but not imported

| Source | Why not |
|---|---|
${NOT_READ.map(([f, w]) => `| \`${f}\` | ${w} |`).join('\n')}

The archive holds ${manifest.fileCount} checksummed files in total.
\`.venv/\`, \`__pycache__/\` and nested \`.git/\` are excluded by declared
pattern — reproducible artefacts, not sources — and the archived
Discogs token is listed without a digest.

## What came from where

### M0-IMPORT-ENRICHED — \`Classical Master\`, ${enriched.rows} rows

All ${enriched.rows} imported. ${enriched.discogsFound} carry a Discogs
match and ${enriched.discogsNotFound} do not.

Which columns Discogs wrote was measured, not assumed: \`Label\`,
\`Discogs ID\`, \`Discogs URL\` and \`Discogs ID Score\` are populated on
exactly the ${enriched.discogsFound} matched rows and none of the
${enriched.discogsNotFound} others. \`Musicians\` and \`Track listing\`
were overwritten by the same pass. Everything else predates it and is
tagged \`legacy\`.

The existing confidence labels are carried as
\`discogs_confidence_legacy\` for M2 to audit, and are never treated as
confidence: 236 rows say "Exact", and 16 of the known-wrong matches are
among them.

### M0-IMPORT-REMEDIAL — \`Classical Remedial\`, ${remedial.sheetRows} rows

${remedial.imported} imported as \`needs-capture\`;
**${remedial.droppedPlaceholders} dropped as placeholders.**

The rule, so it can be disputed: *a row is a placeholder when it
carries no value in any column other than ID.* It needs no judgement
and partitions the sheet exactly
${remedial.droppedPlaceholders}/${remedial.imported}. Every dropped ID
is listed at the end of this report.

\`Label\` is empty on all ${remedial.imported} rows — the "label captured
on 0% of the backlog" finding. The combined label-and-catalogue string
in \`Catalogue #\` was split:

| Outcome | Rows | Meaning |
|---|---|---|
| \`split\` | ${remedial.splitOutcomes.split} | label and catalogue number separated against an attested label |
| \`bare-catno\` | ${remedial.splitOutcomes['bare-catno']} | no label present in the source at all — complete, not failed |
| \`refused\` | ${remedial.splitOutcomes.refused} | could not be split confidently; routed to capture |

Refusal reasons:

${Object.entries(remedial.splitReasons).sort((a, b) => Number(b[1]) - Number(a[1]))
    .map(([r, n]) => `- \`${r}\` — ${n}`).join('\n')}

A wrong label is worse than an absent one, because a wrong label
corroborates a wrong match. Refused rows keep their combined string
intact in \`combined_raw\`, so nothing is lost and a later pass with a
larger label vocabulary can re-split them.

### M0-MERGE-LOAD-FILES — ${load.sheetRows} rows across two files

${load.usable} usable under the same placeholder rule
(${load.sheetRows - load.usable} placeholders dropped).
**${load.merged} merged; ${load.duplicates} were already present.**

The load files had already been folded into \`Classical Remedial\`.
Two independent methods agree: positionally the ${load.usable} rows map
in order onto Remedial rows 59–141, with all ${load.usable} catalogue
strings and all 46 titles identical and only the IDs renumbered; and
the merge's own key-based de-duplication, which knows nothing of row
order, matched all ${load.usable} and merged none.

De-duplication is by catalogue number plus label **with multiplicity**,
so four copies of \`RTL2075 MCPS\` absorb four incoming rows rather than
collapsing into one. ${load.ambiguous} rows were ambiguous.

### M0-IMPORT-AI-WORKS — ${ai.aiRows} rows, joined on source ID

${ai.attached} attached, ${ai.unmatched} unmatched. Adds no rows; tags
values \`guess\`.

**There are no AI ratings.** \`Critical Rating\` is empty in all six AI
Works files that carry the column, including
\`AI_Vinyl_Works_Stage_7 Rating Qualifiers etc.xlsx\`. The AI-invented
ratings the brief warns about were never written. What exists is
${ai.trackListingsFound} AI track listings with confidence
(High/Medium/Low), remarks and sources.

**The AI track listings had already leaked into the sourced data.** On
all ${ai.reclassifiedToGuess} rows where Discogs found nothing,
\`Track listing\` in \`Classical Master\` is byte-identical to the AI
file's value; on none of the ${enriched.discogsFound} matched rows is
it. Those ${ai.reclassifiedToGuess} values were reclassified from
\`legacy\` to \`guess\`.

v2 \`classical Track listings 01.xlsx\` was chosen to override v1 Stage 8
for track listings. It agrees with Stage 8 on all ${ai.v2Agreements}
rows, so the override changed nothing (${ai.v2Overrides} overrides).

## Provenance of every sourced value

| Source | Values | May feed a decision? |
|---|---|---|
${Object.entries(provenance).sort((a, b) => b[1] - a[1])
    .map(([s, n]) => `| \`${s}\` | ${n.toLocaleString('en-GB')} | ${s === 'guess' || s === 'legacy' ? 'never' : 'only once a person confirms it'} |`).join('\n')}

\`decision_eligible\` is a computed column, not an assertion: it is
recomputed after every import so a guessed value cannot make a row
eligible by arriving late.

## Expect these totals to move

This is a record of one pass, not a permanent truth. The counts will
change once the backlog is captured and composers are resolved for the
Various/Unknown rows. What should not change is the rule each count was
produced by — those are stated above so a later disagreement can be
settled against the frozen bytes.

## Dropped placeholder IDs (${remedial.droppedPlaceholders})

From \`Classical Remedial\`, carrying no value in any column but ID:

${droppedIds['M0-IMPORT-REMEDIAL'].join(', ')}

## Duplicate decisions (${mergeDecisions.length})

Each load-file row, the key it matched on, and the dataset row it
matched:

| Source | Row | Key | Decision | Matched |
|---|---|---|---|---|
${mergeDecisions.map((d) => `| ${d.sourceFile.replace(' to add.xlsx', '')} | ${d.sourceRowId} | \`${d.key}\` | ${d.decision} | ${d.matchedItemId} |`).join('\n')}

## Machine-readable summary

\`\`\`json
${JSON.stringify(summary, null, 2)}
\`\`\`
`;

  return { report, rows, summary };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { report, rows, summary } = renderReport();
  // Written from the same in-memory rows the report describes.
  writeFileSync(CSV_OUT, toCsv(rows));
  writeFileSync(REPORT_OUT, report);
  console.log(`build-report: wrote ${CSV_OUT} (${rows.length} rows) and ${REPORT_OUT}`);
  console.log(`  decision-eligible: ${summary.decisionEligibleRows}`);
}
