#!/usr/bin/env node
// @ts-check

/**
 * freeze-archive.mjs — M0-ARCHIVE-FREEZE.
 *
 * Walks the read-only source archive and records a sha256 + byte
 * length for every file, so every later import can name exactly which
 * bytes it read. Write mode produces the manifest; `--check`
 * recomputes and fails on any drift.
 *
 * Deliberately NOT recorded: mtime. This tree lives on OneDrive and
 * sync rewrites timestamps, which would make `--check` fail for
 * reasons that have nothing to do with the bytes.
 *
 * Secrets: files matching SECRET_PATTERNS are listed by path and size
 * with their digest redacted. The manifest is committed; a hash of a
 * live credential is not something to put in git history.
 *
 * Read-only over the archive (AGENTS.md hard rule). Zero dependencies.
 *
 * Usage: node tools/freeze-archive.mjs [--check]
 *                                      [--archive "Pre August 2026"]
 *                                      [--out data/archive-manifest.json]
 */

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/**
 * Present by accident, not by intent. Two kinds, both declared in the
 * manifest so the exclusion is auditable rather than assumed:
 * transient OS/Office droppings, and reproducible build artefacts.
 * The venv alone is 9,106 of the archive's 9,285 files and is not an
 * input to any import — the CLI source beside it is.
 */
const EXCLUDED = [
  { pattern: '.DS_Store', why: 'Finder metadata; rewritten on any folder view' },
  { pattern: '~$*', why: 'Excel lock file; exists only while a book is open' },
  { pattern: '.venv/', why: 'Python virtualenv; reproducible from pyproject.toml' },
  { pattern: '__pycache__/', why: 'Bytecode cache; reproducible from the .py sources' },
  { pattern: '.git/', why: 'Nested repository internals; git is its own manifest' },
];

/** Never digest these into a committed file. */
const SECRET_PATTERNS = ['discogs_personal_access_token'];

/** A trailing `/` marks a directory pattern; `*` a name prefix. */
const isExcludedDir = (/** @type {string} */ name) =>
  EXCLUDED.some(({ pattern }) => pattern.endsWith('/') && pattern.slice(0, -1) === name);

const isExcludedFile = (/** @type {string} */ name) =>
  EXCLUDED.some(({ pattern }) => !pattern.endsWith('/') && (pattern.endsWith('*')
    ? name.startsWith(pattern.slice(0, -1))
    : name === pattern));

const isSecret = (/** @type {string} */ path) =>
  SECRET_PATTERNS.some((p) => path.includes(p));

/** @param {string} dir @param {string} root @returns {string[]} */
function walk(dir, root) {
  /** @type {string[]} */ const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (isExcludedDir(entry.name)) continue;
      out.push(...walk(full, root));
    } else if (entry.isFile() && !isExcludedFile(entry.name)) {
      out.push(relative(root, full));
    }
  }
  return out;
}

const args = process.argv.slice(2);
const argOf = (/** @type {string} */ n, /** @type {string} */ d) => {
  const i = args.indexOf(n);
  return i >= 0 && args[i + 1] ? args[i + 1] : d;
};
const check = args.includes('--check');
const archive = argOf('--archive', 'Pre August 2026');
const outPath = argOf('--out', 'data/archive-manifest.json');

const paths = walk(archive, archive);
const files = paths.map((p) => {
  const bytes = statSync(join(archive, p)).size;
  const secret = isSecret(p);
  return {
    // POSIX separators so a manifest is portable off macOS.
    path: p.split(sep).join('/'),
    bytes,
    sha256: secret ? 'REDACTED-SECRET' : createHash('sha256').update(readFileSync(join(archive, p))).digest('hex'),
  };
});

const manifest = {
  $comment: 'M0-ARCHIVE-FREEZE. Generated by tools/freeze-archive.mjs — never hand-edit. Verify with --check.',
  archive,
  fileCount: files.length,
  totalBytes: files.reduce((n, f) => n + f.bytes, 0),
  excluded: EXCLUDED,
  redacted: SECRET_PATTERNS,
  files,
};

const serialise = (/** @type {any} */ m) => `${JSON.stringify(m, null, 2)}\n`;

if (check) {
  let prior;
  try {
    prior = JSON.parse(readFileSync(outPath, 'utf8'));
  } catch {
    console.error(`freeze-archive --check: no readable manifest at ${outPath}`);
    process.exit(1);
  }
  /** @type {string[]} */ const drift = [];
  const priorBy = new Map(prior.files.map((/** @type {any} */ f) => [f.path, f]));
  const nowBy = new Map(files.map((f) => [f.path, f]));
  for (const [p, f] of nowBy) {
    const was = priorBy.get(p);
    if (!was) drift.push(`ADDED    ${p}`);
    else if (was.sha256 !== f.sha256 || was.bytes !== f.bytes) drift.push(`CHANGED  ${p}`);
  }
  for (const p of priorBy.keys()) if (!nowBy.has(p)) drift.push(`REMOVED  ${p}`);

  if (drift.length) {
    console.error(`freeze-archive --check: FAIL — ${drift.length} drift(s) against ${outPath}`);
    for (const d of drift.slice(0, 40)) console.error(`  ${d}`);
    if (drift.length > 40) console.error(`  … ${drift.length - 40} more`);
    process.exit(1);
  }
  console.log(`freeze-archive --check: OK — ${files.length} files, ${manifest.totalBytes} bytes match ${outPath}`);
} else {
  writeFileSync(outPath, serialise(manifest));
  console.log(`freeze-archive: wrote ${outPath} — ${files.length} files, ${manifest.totalBytes} bytes`);
}
