#!/usr/bin/env node
// @ts-check

/**
 * match-report.mjs — what the full matcher run actually decided.
 *
 * Reads the database rather than the run's JSON, so it describes the
 * state that will be deployed rather than a log of how it got there.
 *
 * Usage: node tools/match-report.mjs [--db data/deep-groove.sqlite]
 */

import { DatabaseSync } from 'node:sqlite';
import { writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
const i = args.indexOf('--db');
// READ-ONLY, deliberately. Opening this read-write while a run holds
// the database killed a 45-minute job with "database is locked".
const db = new DatabaseSync(i >= 0 && args[i + 1] ? args[i + 1] : 'data/deep-groove.sqlite',
  { readOnly: true });

const one = (sql) => db.prepare(sql).get();
const all = (sql) => db.prepare(sql).all();
const n = (sql) => Number(one(sql).n);

const total = n('SELECT COUNT(*) n FROM item');
const matched = n('SELECT COUNT(*) n FROM match_run');
const byState = all('SELECT state, COUNT(*) n FROM match_run GROUP BY state ORDER BY n DESC');
const errors = n("SELECT COUNT(*) n FROM match_run WHERE state = 'error'");
const eligible = n('SELECT COUNT(*) n FROM v_decision_eligible_item');

/** How auto-accepted rows were corroborated — the gate's own evidence. */
const families = all(`
  SELECT c.signals_json FROM match_run m
    JOIN match_candidate c ON c.match_run_id = m.id AND c.rank = 1
   WHERE m.state = 'auto-accepted'`);
const famCount = new Map();
for (const row of families) {
  for (const f of JSON.parse(row.signals_json).families ?? []) famCount.set(f, (famCount.get(f) ?? 0) + 1);
}

/** Where the backlog stands, since those rows behave differently. */
const backlog = all(`
  SELECT m.state, COUNT(*) n FROM match_run m
    JOIN item i ON i.id = m.item_id
   WHERE i.import_ref LIKE 'DG-%'
     AND EXISTS (SELECT 1 FROM capture c WHERE c.item_id = i.id AND c.label_raw IS NULL)
   GROUP BY m.state ORDER BY n DESC`);

const queueSample = all(`
  SELECT m.item_id, c.catno_raw, c.title_raw,
         (SELECT COUNT(*) FROM match_candidate mc WHERE mc.match_run_id = m.id) cands,
         json_extract(m.queries_json, '$.reason') reason
    FROM match_run m LEFT JOIN capture c ON c.item_id = m.item_id
   WHERE m.state = 'needs-review' ORDER BY m.item_id LIMIT 12`);

/**
 * Query failures per row — the measurement M2-DISCOGS-PACING needs to
 * pick an interval instead of guessing at one. Older runs predate the
 * counts and report NULL; they are counted separately rather than as
 * zero failures, because "not recorded" and "none failed" are the two
 * answers it would be worst to confuse here.
 */
const pacing = one(`
  SELECT COUNT(*)                                                    AS runs,
         SUM(json_extract(queries_json, '$.queriesRun')  IS NULL)    AS unrecorded,
         SUM(COALESCE(json_extract(queries_json, '$.queriesRun'), 0)) AS ran,
         SUM(COALESCE(json_extract(queries_json, '$.queryErrors'), 0)) AS failed,
         SUM(COALESCE(json_extract(queries_json, '$.queryErrors'), 0) > 0) AS rowsWithFailures
    FROM match_run`);
const recorded = Number(pacing.runs) - Number(pacing.unrecorded ?? 0);
const failRate = Number(pacing.ran) > 0
  ? `${((Number(pacing.failed) / Number(pacing.ran)) * 100).toFixed(1)}%` : '—';

const pct = (x) => `${((x / Math.max(matched, 1)) * 100).toFixed(1)}%`;

writeFileSync('data/match-report.md', `# Matcher run

<!-- GENERATED by tools/match-report.mjs from the database.
     Regenerate: node tools/match-run.mjs && node tools/match-report.mjs -->

**${matched} of ${total} items have been matched.** ${eligible} are decision-eligible,
which is correct: the matcher writes \`discogs\` unconfirmed, and only a
person working the review queue can confirm.

## What the gate decided

| Outcome | Rows | Share |
|---|---|---|
${byState.map((r) => `| \`${r.state}\` | ${r.n} | ${pct(Number(r.n))} |`).join('\n')}

${errors ? `**${errors} rows errored** — they were never successfully searched and must be
re-queued. A row that never reached Discogs is not a row with no match.`
    : 'No rows errored, so every outcome above is a real result rather than a swallowed failure.'}

## How the auto-accepted rows were corroborated

The gate needs two independent families agreeing, a score of 80 and a
margin of 25 over the runner-up. Among the accepted rows, families
fired as:

| Family | Rows |
|---|---|
${[...famCount].sort((a, b) => b[1] - a[1]).map(([f, c]) => `| ${f} | ${c} |`).join('\n') || '| — | — |'}

## The backlog behaves differently, and should

${backlog.map((r) => `- \`${r.state}\`: ${r.n}`).join('\n') || '- none yet'}

Label is captured on 0% of the backlog rows, so a catalogue number is
usually the only human signal they carry. One family cannot clear a
two-family gate, so these correctly land in review rather than being
auto-accepted. **They want capture, not matching** — which is what the
capture screen is for.

## A sample of the queue

| Item | Catalogue | Title | Candidates | Why it was not accepted |
|---|---|---|---|---|
${queueSample.map((r) => `| ${r.item_id} | \`${r.catno_raw ?? '—'}\` | ${String(r.title_raw ?? '—').slice(0, 30)} | ${r.cands} | ${String(r.reason ?? '').slice(0, 60)} |`).join('\n')}

Clear it at \`/review.html\`: \`1\`–\`5\` choose, \`N\` none, \`S\` skip, \`B\` back.

## Pacing — how many queries are being refused

Every failed rung is lost recall: the best match may have been in one
of them. This is the number to watch when widening the Discogs gap,
which is tunable without a deploy —
\`wrangler kv key put --binding=CACHE rl:discogs:min-interval 3000\`.
The override may only widen the gap, never narrow it, and the batch
size follows it so a tick stays the same length.

| Measure | Value |
|---|---|
| Runs with counts recorded | ${recorded} of ${pacing.runs} |
| Queries run | ${pacing.ran} |
| Queries failed | ${pacing.failed} (${failRate}) |
| Rows with at least one failed query | ${pacing.rowsWithFailures} |

${Number(pacing.unrecorded ?? 0) > 0
    ? `${pacing.unrecorded} run(s) predate the counts and are excluded rather than \
counted as clean — re-verify to bring them in.`
    : 'Every run carries its counts.'}
`);

console.log(`match-report: ${matched}/${total} matched, ${eligible} eligible, ${errors} errored -> data/match-report.md`);
