#!/usr/bin/env node
// @ts-check

/**
 * photo-score.mjs — SPIKE-PHOTO-TO-FIELDS, the judging half.
 *
 * Scores what the chat read against what a person typed off the same
 * records, and answers the one question the record poses: does the
 * model refuse more often than it is wrong?
 *
 * A single accuracy percentage would hide that, which is why it is not
 * reported. `refused` costs a re-read of a photo already taken.
 * `wrong` costs a bad Discogs match that corroborates itself — the 9%
 * M0 measured. They are not interchangeable and must not be averaged.
 *
 * IT NEVER TOUCHES THE DATABASE, and a test asserts it cannot.
 *
 * Usage:
 *   node tools/photo-score.mjs [--extract data/photo-extract.json]
 *                              [--truth data/label-photos/ground-truth.csv]
 *                              [--out data/photo-score.md]
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { readCsv } from './lib/csv.mjs';
import { scoreOne, trapSprung, summarise, PHOTO_FIELDS, ROTATIONS } from './lib/photo-fields.mjs';

const args = process.argv.slice(2);
const argOf = (n, d) => { const i = args.indexOf(n); return i >= 0 && args[i + 1] ? args[i + 1] : d; };

const extractPath = argOf('--extract', 'data/photo-extract.json');
const truthPath = argOf('--truth', 'data/label-photos/ground-truth.csv');
const outPath = argOf('--out', 'data/photo-score.md');

for (const [path, what] of [[extractPath, 'an imported chat reply'], [truthPath, 'typed ground truth']]) {
  if (!existsSync(path)) {
    console.error(`Missing ${path} — the spike needs ${what}.`);
    console.error('See data/label-photos/README.md.');
    process.exit(2);
  }
}

const run = JSON.parse(readFileSync(extractPath, 'utf8'));
const truthRows = readCsv(readFileSync(truthPath, 'utf8'));

/** Ground truth keyed by row id, with the decoys split out of one cell. */
const truth = new Map(truthRows.map((r) => [r.row_id, {
  ...r,
  decoy_numbers: (r.decoy_numbers ?? '').split(';').map((s) => s.trim()).filter(Boolean),
}]));

const rows = [];
const untyped = [];
/**
 * Rows whose answer existed before the reading did.
 *
 * A reader with repository access can open the ground truth however
 * firmly the prompt asks it not to, so independence cannot be assumed —
 * it has to be recorded. `photo-import` stamps it at the only moment it
 * is knowable, and these rows are held out of the headline: they are
 * still shown, because a wrong value is worth seeing whatever the
 * circumstances, but they cannot earn a pass.
 */
const notIndependent = [];
for (const [rowId, result] of Object.entries(run.results ?? {})) {
  const want = truth.get(rowId);
  if (!want) { untyped.push(rowId); continue; }
  const row = {
    rowId,
    verdicts: scoreOne(result.fields, want),
    trap: trapSprung(result.fields, want),
    fields: result.fields,
    turned: Object.values(result.fields?.rotate_cw ?? {})
      .filter((d) => Number(d) > 0).length,
  };
  (result.truthPreexisting || result.declaredNotIndependent ? notIndependent : rows).push(row);
}

// Named rather than counted: a row typed but never read is a gap in the
// round trip, and a score that quietly omits it overstates coverage.
const unread = [...truth.keys()].filter((id) => !run.results?.[id]);

if (!rows.length) {
  console.error('No row has both a reading and a typed ground-truth row that');
  console.error('postdates it.');
  if (notIndependent.length) {
    console.error(`\n${notIndependent.length} row(s) were read AFTER their answer was typed:`);
    console.error(`  ${notIndependent.map((r) => r.rowId).join(', ')}`);
    console.error('\nThose cannot measure anything — the reader could have looked it up.');
    console.error('Photograph, read, and only then type what the label says.');
  }
  process.exit(2);
}

const s = summarise(rows);
const pct = (n) => `${((n / (s.photos * PHOTO_FIELDS.length)) * 100).toFixed(1)}%`;
const lines = [
  '# Photo-to-fields: what the model read',
  '',
  `Generated by \`tools/photo-score.mjs\` over ${s.photos} independently-read label photo(s), `
    + `read by \`${run.model ?? 'unknown chat'}\` via ${run.source ?? 'chat'}.`,
  '',
  '## The bar',
  '',
  `**${s.passes ? 'PASSES' : 'FAILS'}** — the record asks that refusals beat wrong answers `
    + 'and that no decoy number is reported as a catalogue number.',
  '',
  `- exact: **${s.totals.exact}** (${pct(s.totals.exact)} of all fields)`,
  `- refused: **${s.totals.refused}** — a re-read of a photo already taken`,
  `- wrong: **${s.totals.wrong}** — must be fewer than refusals`,
  `- correctly absent: ${s.totals.correctlyAbsent}`,
  `- **decoy numbers reported as catalogue numbers: ${s.totals.trapsSprung}** — must be 0`,
  '',
  '## Per field',
  '',
  '| field | exact | wrong | refused | correctly absent | invented |',
  '| --- | ---: | ---: | ---: | ---: | ---: |',
  ...PHOTO_FIELDS.map((f) => {
    const p = s.per[f];
    return `| \`${f}\` | ${p.exact} | ${p.wrong} | ${p.refused} | ${p['correctly-absent']} | ${p.invented} |`;
  }),
  '',
];

const misses = rows.flatMap((r) => PHOTO_FIELDS
  .filter((f) => r.verdicts[f] === 'wrong' || r.verdicts[f] === 'invented')
  .map((f) => `- \`${r.rowId}\` **${f}**: read \`${r.fields[f]}\`, label says \`${truth.get(r.rowId)[f] || '(nothing)'}\``));
if (misses.length) lines.push('## Every wrong value', '', ...misses, '');

const sprung = rows.filter((r) => r.trap);
if (sprung.length) {
  lines.push('## Decoy numbers taken for catalogue numbers', '',
    'This is the M0 failure recreated: a number treated as a verdict.', '',
    ...sprung.map((r) => `- \`${r.rowId}\`: reported \`${r.fields.catno_raw}\``), '');
}

if (notIndependent.length) {
  const bad = notIndependent.filter((r) => PHOTO_FIELDS.some(
    (f) => r.verdicts[f] === 'wrong' || r.verdicts[f] === 'invented') || r.trap);
  lines.push('## Held out — the answer existed before the reading', '',
    'Either the answer existed before the reading did, or the reader'
      + ' declared it carried prior context about these records. Both cost'
      + ' independence, and only the first is detectable here — the second is'
      + ' taken on the reader\'s word.', '',
    ...notIndependent.map((r) => `- \`${r.rowId}\``), '');
  if (bad.length) {
    lines.push('Worth looking at anyway — a wrong value is a wrong value:', '',
      ...bad.map((r) => `- \`${r.rowId}\``), '');
  }
}

/**
 * How the writing sat, and whether it cost anything.
 *
 * The question behind this is whether a rotation-detector is worth
 * building. It only is if photographs arrive rotated AND rotated ones
 * read worse — two facts, both cheap to read off a run and neither
 * worth guessing at. A table beats an opinion.
 */
const oriented = [...rows, ...notIndependent];
if (oriented.length) {
  const withTurned = oriented.filter((r) => r.turned > 0);
  const images = oriented.reduce((n, r) => n + r.turned, 0);
  lines.push('## How the writing sat', '',
    'Reported per image, as degrees clockwise to stand it upright.', '');
  lines.push(images
    ? `${images} photograph(s) across ${withTurned.length} record(s) arrived turned. `
      + '`node tools/photo-rotate.mjs` stands them up from this reading; re-pack and read those again.'
    : 'No photograph was reported as needing turning.', '');
  if (withTurned.length) {
    const cost = (rs) => {
      const w = rs.reduce((n, r) => n + PHOTO_FIELDS.filter(
        (f) => r.verdicts[f] === 'wrong' || r.verdicts[f] === 'invented').length, 0);
      return rs.length ? (w / rs.length).toFixed(2) : '—';
    };
    lines.push('| records | wrong values per record |', '| --- | ---: |',
      `| with a turned photograph (${withTurned.length}) | ${cost(withTurned)} |`,
      `| all upright (${oriented.length - withTurned.length}) | `
        + `${cost(oriented.filter((r) => !r.turned))} |`, '');
  }
}

if (unread.length || untyped.length) {
  lines.push('## Coverage gaps', '');
  if (unread.length) lines.push(`- typed but never read back: ${unread.join(', ')}`);
  if (untyped.length) lines.push(`- read but not yet typed: ${untyped.join(', ')}`);
  lines.push('');
}

writeFileSync(outPath, `${lines.join('\n')}\n`);
console.log(lines.join('\n'));
console.log(`\nWrote ${outPath}`);
process.exit(s.passes ? 0 : 1);
