#!/usr/bin/env node
// @ts-check

/**
 * reverify-report.mjs — turns the audit's JSON into something a person
 * can read and disagree with. Committed; the JSON it reads is not.
 *
 * Usage: node tools/reverify-report.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';

const d = JSON.parse(readFileSync('data/reverify.json', 'utf8'));
const bad = d.findings.filter((f) => f.verdict === 'unsupported');
const sup = d.findings.filter((f) => f.verdict === 'supported');
const noPeople = sup.filter((f) => !f.families.includes('people'));

const tally = (rows, key) => {
  const m = new Map();
  for (const r of rows) m.set(key(r), (m.get(key(r)) ?? 0) + 1);
  return [...m].sort((a, b) => b[1] - a[1]);
};

const row = (f) => `| ${f.itemId} | ${f.legacyConfidence} | ${f.score} | ${f.families.join(', ') || '—'} `
  + `| \`${f.capture.catno ?? '—'}\` | ${(f.discogs.label ?? '—')} — ${String(f.discogs.title ?? '').slice(0, 44)} |`;

writeFileSync('data/reverify-report.md', `# Re-verification report

<!-- GENERATED by tools/reverify-report.mjs from data/reverify.json.
     Regenerate: node tools/reverify.mjs && node tools/reverify-report.mjs -->

Every row that already claimed a Discogs release, re-examined against
the corroboration gate. Audited ${d.audited} rows.

**${d.unsupported} are not supported by independent human evidence**, ${d.exactButUnsupported} of them
labelled "Exact" by the old pipeline.

## What "unsupported" means, and what it does not

The audit scores the claimed release against **only what a person
supplied**, judged by recorded provenance. On these rows the \`label\`
column came from Discogs, so letting it corroborate would compare
Discogs with itself — a first run did that and reported 1 unsupported
out of ${d.audited}, which measured nothing.

Unsupported means *not corroborated*, which is not the same as
*wrong*. Some of the rows below are probably correct and merely
thinly evidenced. All of them belong in the review queue, where a
person decides.

## The ${d.unsupported} unsupported matches

| Item | Old label | Score | Families agreeing | Captured catno | What Discogs returned |
|---|---|---|---|---|---|
${bad.map(row).join('\n')}

Several are unambiguously a different record — a catalogue number is
unique per label, not globally, which is exactly the failure the gate
exists to catch.

## How the old confidence labels held up

| Old label | Supported | Unsupported |
|---|---|---|
${tally(d.findings, (f) => f.legacyConfidence).map(([label]) => {
  const s = sup.filter((f) => f.legacyConfidence === label).length;
  const u = bad.filter((f) => f.legacyConfidence === label).length;
  return `| ${label} | ${s} | ${u} |`;
}).join('\n')}

"Exact" is not a verdict: it failed ${d.exactButUnsupported} times. "Fallback" failed
${bad.filter((f) => f.legacyConfidence === 'Fallback').length} times out of
${d.findings.filter((f) => f.legacyConfidence === 'Fallback').length}, so the labels
carry some signal — just not enough to act on.

## Where the remaining risk is

${noPeople.length} of the ${sup.length} supported rows carry **no people evidence**: they
rest on catalogue number, title and format. ${noPeople.filter((f) => !f.discogs.year).length} of those also
have no release year. They pass the gate and are the likeliest place
for a wrong match to be hiding, because a generic compilation title
plus a colliding catalogue number can clear 80 on its own.

## On the brief's figure of 26

The brief states that 26 of 277 matches point at a different record.
This audit finds ${d.unsupported}. The two are **different measurements** and are not
reconcilable from the data: the brief does not say which rows it meant
or how they were identified, so there is nothing to compare against.
What can be said is that the gate catches real errors — a classical
conductor matched to a heavy metal album, a Classics for Pleasure
number matched to a Fontana pop single — and that settling the rest
needs the full search-based run through the review queue, not this
narrower audit of existing claims.
`);
console.log(`reverify-report: wrote data/reverify-report.md (${d.unsupported} unsupported of ${d.audited})`);
